repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.14.8
    hooks:
      - id: typos
        # Quick fix for known issue.
        # https://github.com/crate-ci/typos/issues/347#issuecomment-1059926087
        exclude: themes
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
    - id: markdownlint
      args:
        - --ignore=themes
